### ISSUE TITLE
[install] Configure GRUB to use a label

### ISSUE THREAD

**Issue by LukeShortCloud** [winesapOS/winesapOS#935]
I believe that using a label for the root file system in GRUB will make booting more reliable. This should help fix Ventoy support.

Related: https://github.com/LukeShortCloud/winesapOS/issues/836

**Comment by LukeShortCloud** [comment]
Some hints are provided here: https://ubuntuforums.org/showthread.php?t=2446277

**Comment by LukeShortCloud** [comment]
https://forums.linuxmint.com/viewtopic.php?f=46&t=38599

**Comment by LukeShortCloud** [comment]
@takeonelayer That's amazing, thank you for helping to test and confirm all of this!

Did you manually create the `/boot/grub/grub.cfg` configuration file? Or are you using `grub-mkconfig` to automatically generate it? I'm primarily curious in how you created the GRUB configuration using the "by-label GRUB config". Is there an option for that in `/etc/default/grub`?

I'd like to find a way to automate all of this. The `root=LABEL=winesapos-root` is a bit tricky. Maybe there is a hook we can use to run a script after the `grub-mkconfig` has been used. On the bright side, I already converted the `vtoyboosh.sh` script so it can work inside of our builds of winesapOS. We're close to having images with Ventoy support baked in!

**Comment by takeonelayer** [comment]
I'm automatically generating it with grub-mkconfig.

The last comment from your posted link lead me to the solution.
https://forums.linuxmint.com/viewtopic.php?p=296417#p296417

It's a 14 years old thread. So syntax has changed. I only extracted useful lines from the original script:

/etc/grub.d/10_linux

> auto_label="`e2label ${GRUB_DEVICE_BOOT} 2>/dev/null`"
> linux_root_device_thisversion="LABEL=${auto_label}

(maybe we can use e2label here in `10_linux` just fine, but it doesn't compile in grub-mkconfig_lib. I eventually changed both file to hardcoded label though.)

(searched for linux_root_device_thisversion, it existed in serveral places, essentially most of them need to change to the above syntax except for the PARTUUID condition because we are going to disable this approach in /etc/default/grub)

> linux	${rel_dirname}/${basename} root=${linux_root_device_thisversion} ro ${args}

(and this line is located elsewhere/declared ahead in the file in modern GRUB version)

/usr/lib/grub/grub-mkconfig_lib 

> \# If there's a filesystem UUID that GRUB is capable of identifying, use it;
> \# otherwise set root as per value in device.map.
> echo "set root='`${grub_probe} --device ${device} --target=drive`'"
> 
> auto_label="`e2label ${device} 2>/dev/null`"
> echo "search --no-floppy --label ${auto_label} --set root"

(the `${device}` needs to be changed to `$@` to match our newer context of the file)
echo "set root='`${grub_probe} --device $@ --target=drive`'"
manual_label=winesapos-root
echo "search --no-floppy --label ${manual_label} --set root"
(yah, tricky indeed..)

/etc/defaults/grub

> GRUB_DISABLE_LINUX_UUID="true"

(apart from the UUID, I also disabled PARTUUID)
GRUB_DISABLE_LINUX_UUID="true"
GRUB_DISABLE_LINUX_PARTUUID="true"

**Comment by takeonelayer** [comment]
[by-label-grub-config.zip](https://github.com/user-attachments/files/16765500/by-label-grub-config.zip)

@LukeShortCloud  Here're my modified files as an example.

/usr/share/grub/grub-mkconfig_lib      (/usr/share instead of /usr/lib from the original post)
/etc/grub.d/10_linux
/etc/defaults/grub

/boot/grub/grub.cfg   (the final output file)
