### ISSUE TITLE
nvidia drm

### ISSUE THREAD

**Issue by AireagoirSteam** [winesapOS/winesapOS#975]
more of a request/enhancement and possably related to the gamescope steam bug.
gamescope requires nvidia-drm.modeset=1 setting for the kernel for nvidia hardware.

**Comment by LukeShortCloud** [comment]
Hey @AireagoirSteam , thanks for the suggestion!

Out-of-the-box we use the open source Nouveau driver. If a user selects the open kernel module driver for NVIDIA instead during the first-time setup, we do set `nvidia_drm.modeset=1`. Wayland support would not work at all otherwise. NVIDIA also recently revealed that they will soon enable that by default in an upcoming driver update. I'm guessing that will either be the stable 565 release or the future 570 release.

https://github.com/winesapOS/winesapOS/blob/4.1.0/scripts/winesapos-setup.sh#L432

The Gamescope slowness bug with Steam is more of an issue with the Steam client. It supports hardware acceleration with NVIDIA on Linux but it's disabled by default. For comparison, both Open Gamepad UI and Playtron ran through Gamescope Session are not slow on NVIDIA.

**Comment by AireagoirSteam** [comment]
Apparently nvidia-drm.fbdev=1 is also needed after a certain kernel version.
I added both and after some ordering got gamescope working.
could the nvidia-drm.fbdev=1 be added as well by default?

**Comment by LukeShortCloud** [comment]
Nice, glad to hear you got Gamescope working! We also enable `nvidia_drm.fbdev=1` by default. If you have any more suggestions, we're always open to new ideas. :-)
